# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['clone_hero_client.py'],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports=[
        'colorama',
        'colorama.win32',
        'colorama.winterm',
        'requests',
        'urllib3',
        'certifi',
        'charset_normalizer',
        'idna',
        'watchdog',
        'watchdog.observers',
        'watchdog.events',
        'pystray',
        'pystray._base',
        'pystray._win32',
        'PIL',
        'PIL.Image',
        'PIL.ImageDraw',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='CloneHeroScoreTracker_v2.4.13',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
