# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['clone_hero_client.py'],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports=[
        'colorama',
        'colorama.win32',
        'colorama.winterm',
        'requests',
        'urllib3',
        'certifi',
        'charset_normalizer',
        'idna',
        'watchdog',
        'watchdog.observers',
        'watchdog.events',
        'pystray',
        'pystray._base',
        'pystray._win32',
        'PIL',
        'PIL.Image',
        'PIL.ImageDraw',
        # Bridge integration dependencies
        'psutil',
        'win32com',
        'win32com.client',
        'pythoncom',
        'pywintypes',
        'websocket',
        'websocket._core',
        'websocket._http',
        'websocket._handshake',
        'websocket._socket',
        'websocket._url',
        # MIDI parsing for charts
        'mido',
        'mido.midifiles',
        'mido.midifiles.midifiles',
        'mido.midifiles.tracks',
        'mido.midifiles.meta',
        'mido.messages',
        'mido.messages.messages',
        'mido.parser',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='CloneHeroScoreTracker_v2.6.2',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
